# Generated by Django 6.0.5 on 2026-06-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=100)),
                ('clause_text', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('reason', models.TextField()),
                ('suggestion', models.TextField()),
                ('page_number', models.IntegerField(default=0)),
                ('start_char', models.IntegerField(default=0)),
                ('end_char', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='contracts.contract')),
            ],
            options={
                'ordering': ['-risk_level', 'clause_type'],
            },
        ),
    ]
