# Generated by Django 6.0.5 on 2026-06-03 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_clauseflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clauseflag',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_flags', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='clauseflag',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clauseflag',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
