# Generated by Django 6.0.5 on 2026-06-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_clauseflag_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clauseflag',
            name='redline',
            field=models.TextField(blank=True, default=''),
        ),
    ]
