# Generated by Django 6.0.5 on 2026-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_clauseflag_redline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='risk_score_value',
            field=models.IntegerField(default=0),
        ),
    ]
